// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomePageDocumentDataSlicesSlice = never;

/**
 * Content for home page documents
 */
interface HomePageDocumentData {
  /**
   * Page Title field in *home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title
   * - **API ID Path**: home_page.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  page_title: prismic.KeyTextField;

  /**
   * Slice Zone field in *home page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice>; /**
   * Meta Title field in *home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *home page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;
}

/**
 * home page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

type ListPageDocumentDataSlicesSlice = never;

/**
 * Content for list page documents
 */
interface ListPageDocumentData {
  /**
   * Title List field in *list page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title
   * - **API ID Path**: list_page.title_list
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title_list: prismic.KeyTextField;

  /**
   * Slice Zone field in *list page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: list_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ListPageDocumentDataSlicesSlice>; /**
   * Meta Title field in *list page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: list_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *list page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: list_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;
}

/**
 * list page document from Prismic
 *
 * - **API ID**: `list_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ListPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ListPageDocumentData>,
    "list_page",
    Lang
  >;

/**
 * Item in *Post Page → Emails*
 */
export interface PostPageDocumentDataEmailsItem {
  /**
   * Email field in *Post Page → Emails*
   *
   * - **Field Type**: Text
   * - **Placeholder**: email@email.fr
   * - **API ID Path**: post_page.emails[].email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email: prismic.KeyTextField;
}

type PostPageDocumentDataSlicesSlice = never;

/**
 * Content for Post Page documents
 */
interface PostPageDocumentData {
  /**
   * Job Title field in *Post Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Title
   * - **API ID Path**: post_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Job Description field in *Post Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: descirption
   * - **API ID Path**: post_page.job_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  job_description: prismic.KeyTextField;

  /**
   * Job Date field in *Post Page*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Date
   * - **API ID Path**: post_page.job_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  job_date: prismic.DateField;

  /**
   * Emails field in *Post Page*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: post_page.emails[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  emails: prismic.GroupField<Simplify<PostPageDocumentDataEmailsItem>>;

  /**
   * Slice Zone field in *Post Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: post_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<PostPageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Post Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: post_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Post Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: post_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Post Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: post_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Post Page document from Prismic
 *
 * - **API ID**: `post_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PostPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<PostPageDocumentData>,
    "post_page",
    Lang
  >;

type ProfilPageDocumentDataSlicesSlice = never;

/**
 * Content for Profil Page documents
 */
interface ProfilPageDocumentData {
  /**
   * Welcome Title field in *Profil Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Welcome
   * - **API ID Path**: profil_page.welcome_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  welcome_title: prismic.KeyTextField;

  /**
   * Subtitle 1 field in *Profil Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Subtitle
   * - **API ID Path**: profil_page.subtitle_1
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle_1: prismic.KeyTextField;

  /**
   * Subtitle 2 field in *Profil Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Subtitle 2
   * - **API ID Path**: profil_page.subtitle_2
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle_2: prismic.KeyTextField;

  /**
   * Slice Zone field in *Profil Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: profil_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ProfilPageDocumentDataSlicesSlice>; /**
   * Meta Title field in *Profil Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: profil_page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Profil Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: profil_page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Profil Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: profil_page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Profil Page document from Prismic
 *
 * - **API ID**: `profil_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProfilPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProfilPageDocumentData>,
    "profil_page",
    Lang
  >;

export type AllDocumentTypes =
  | HomePageDocument
  | ListPageDocument
  | PostPageDocument
  | ProfilPageDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      ListPageDocument,
      ListPageDocumentData,
      ListPageDocumentDataSlicesSlice,
      PostPageDocument,
      PostPageDocumentData,
      PostPageDocumentDataEmailsItem,
      PostPageDocumentDataSlicesSlice,
      ProfilPageDocument,
      ProfilPageDocumentData,
      ProfilPageDocumentDataSlicesSlice,
      AllDocumentTypes,
    };
  }
}
