import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/header";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fr"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col">
      <Header/>
      <div className="w-full h-2 bg-primary"></div>
      <div className="relative h-[100px] w-full overflow-hidden">
        <Image src="/landingImage.jpg" alt="landing image" fill
             sizes="100vw"
             className="object-cover" />
      </div>
      {children}
      </body>
    </html>
  );
}
